terms:
- id: faculty
  term: "Faculty"
  active: true
- id: staff
  term: "Staff"
  active: true
- id: graduate
  term: "Graduate Student"
  active: true
- id: undergraduate
  term: "Undergraduate Student"
  active: true
- id: public
  term: "Public"
  active: true